# Generated by Django 5.1.4 on 2026-09-28 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polaris', '0014_auto_20220211_0624'),
        ('verso_integrations', '0008_sep24withdrawmeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ledger', models.PositiveIntegerField()),
                ('onchain_balance', models.DecimalField(decimal_places=7, max_digits=20)),
                ('internal_balance', models.DecimalField(decimal_places=7, max_digits=20)),
                ('delta', models.DecimalField(decimal_places=7, max_digits=20)),
                ('events_total', models.PositiveIntegerField(default=0)),
                ('unmatched_count', models.PositiveIntegerField(default=0)),
                ('open_discrepancies', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('mismatch', 'Mismatch'), ('skipped', 'Skipped')], max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('network_passphrase', models.CharField(max_length=128)),
                ('hot_wallet', models.CharField(max_length=56)),
                ('asset_contract_id', models.CharField(max_length=56)),
                ('start_ledger', models.PositiveIntegerField()),
                ('cursor', models.CharField(blank=True, default='', max_length=64)),
                ('last_processed_ledger', models.PositiveIntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=7, max_digits=20)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reconciliation sync state',
                'verbose_name_plural': 'Reconciliation sync state',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stellar_tx_hash', models.CharField(db_index=True, max_length=64)),
                ('amount_usdc', models.DecimalField(decimal_places=7, max_digits=20)),
                ('amount_pen', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, max_length=8)),
                ('kyc_status', models.CharField(default='unknown', max_length=32)),
                ('fiat_rail', models.CharField(blank=True, default='', max_length=32)),
                ('fiat_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('sent', 'Sent'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=20)),
                ('anchor_callback_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(choices=[('transfer', 'Transfer'), ('mint', 'Mint'), ('burn', 'Burn'), ('clawback', 'Clawback')], max_length=16)),
                ('ledger', models.PositiveIntegerField(db_index=True)),
                ('ledger_closed_at', models.DateTimeField()),
                ('from_address', models.CharField(blank=True, default='', max_length=69)),
                ('to_address', models.CharField(blank=True, default='', max_length=69)),
                ('counterparty', models.CharField(blank=True, default='', max_length=69)),
                ('memo_raw', models.CharField(blank=True, default='', max_length=128)),
                ('memo_type', models.CharField(blank=True, default='', max_length=8)),
                ('match_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('classified', 'Classified')], db_index=True, default='pending', max_length=16)),
                ('match_kind', models.CharField(blank=True, default='', max_length=32)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiat_deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='verso_integrations.fiatdeposit')),
                ('polaris_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polaris.transaction')),
            ],
            options={
                'verbose_name': 'Stellar ledger entry',
                'verbose_name_plural': 'Stellar ledger entries',
                'ordering': ['ledger', 'event_id'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('balance_mismatch', 'Balance mismatch'), ('unmatched_inbound', 'Unmatched inbound'), ('unmatched_outbound', 'Unmatched outbound'), ('amount_mismatch', 'Amount mismatch'), ('missing_onchain', 'Missing on-chain'), ('worker_stale', 'Worker stale'), ('test', 'Test')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning')], max_length=16)),
                ('dedupe_key', models.CharField(db_index=True, max_length=128)),
                ('expected', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('actual', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('message', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('funding', 'Funding'), ('manual_transfer', 'Manual transfer'), ('fixed', 'Fixed'), ('false_positive', 'False positive'), ('auto_cleared', 'Auto cleared')], default='', max_length=32)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('polaris_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polaris.transaction')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies', to='reconciliation.ledgerentry')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies', to='reconciliation.reconciliationrun')),
            ],
            options={
                'verbose_name_plural': 'Discrepancies',
                'ordering': ['-detected_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('dedupe_key',), name='recon_unique_open_dedupe_key')],
            },
        ),
    ]
