# Generated by Django 5.2.16 on 2026-08-14 01:05

import verso_integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiatDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stellar_account', models.CharField(help_text='Client Stellar account (G...) — same account used for SEP-10.', max_length=56, validators=[verso_integrations.models.validate_stellar_public_key])),
                ('amount_pen', models.DecimalField(decimal_places=2, help_text='PEN amount the client should transfer via CCI/CCE (simulated).', max_digits=18)),
                ('amount_usdc', models.DecimalField(decimal_places=7, help_text='USDC amount to send on-chain after fiat is confirmed.', max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending (awaiting bank transfer)'), ('fiat_confirmed', 'Fiat confirmed'), ('disbursed', 'USDC disbursed')], db_index=True, default='pending', max_length=20)),
                ('bank_instructions', models.JSONField(blank=True, default=dict, help_text='Simulated CCI/CCE transfer instructions shown to the client.')),
                ('stellar_tx_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'simulated fiat deposit',
                'verbose_name_plural': 'simulated fiat deposits',
                'ordering': ['-created_at'],
            },
        ),
    ]
