# Generated by Django 5.2.17 on 2026-08-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso_integrations', '0002_fiatdeposit_tipo_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatdeposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (awaiting bank transfer)'), ('fiat_confirmed', 'Fiat confirmed'), ('disbursing', 'Disbursing (in progress)'), ('disbursed', 'USDC disbursed')], db_index=True, default='pending', max_length=20),
        ),
    ]
