# Generated by Django 5.2.17 on 2026-09-09 22:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso_integrations', '0004_sep24depositmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatdeposit',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, help_text='Tipo de cambio: PEN por 1 USDC — obtenido automáticamente de VERSO (rate_venta) al crear el depósito.', max_digits=12),
        ),
    ]
