# Generated by Django 5.1.4 on 2026-09-27 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0014_auto_20220211_0624'),
        ('verso_integrations', '0007_sep24depositmeta_fiat_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sep24WithdrawMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiat_currency', models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD')], db_index=True, default='PEN', help_text='Fiat currency paid to the client in this SEP-24 off-ramp.', max_length=3)),
                ('amount_usdc', models.DecimalField(decimal_places=7, max_digits=18)),
                ('amount_pen', models.DecimalField(decimal_places=2, help_text='Fiat amount the client receives (PEN or USD).', max_digits=18)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, help_text='rate_compra (fiat per 1 USDC) at quote time.', max_digits=12)),
                ('sell_asset', models.TextField(help_text='SEP-38 asset id sold by user on-chain (stellar:USDC:...).')),
                ('buy_asset', models.TextField(help_text='SEP-38 asset id paid off-chain (iso4217:PEN or iso4217:USD).')),
                ('payout_bank_details', models.JSONField(blank=True, default=dict)),
                ('payout_confirmed_at', models.DateTimeField(blank=True, db_index=True, help_text='When the client submitted their payout CCI details.', null=True)),
                ('fiat_sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verso_withdraw_meta', to='polaris.transaction')),
            ],
            options={
                'verbose_name': 'SEP-24 withdrawal (fiat off-ramp)',
                'verbose_name_plural': 'SEP-24 withdrawals (fiat off-ramp)',
            },
        ),
    ]
